import type { Metadata } from "next";
import { Jost, Cabin, Overpass } from "next/font/google";
import "./globals.css";
import ChatBotAI from "./chatbot/ChatBotAI";

const overpass = Overpass({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Social Learning",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={overpass.className}>
        {children}
        <ChatBotAI />
      </body>
    </html>
  );
}
